import os
import yaml
from typing import Any, Dict
from loguru import logger
from src.healing.audit_logger import AuditLogger
from src.healing.prompt_optimizer import PromptOptimizer

class FixExecutor:
    """
    Executes or suggests corrective actions (fixes) generated by the debugging agent.
    Supports three execution modes: 'suggest', 'semi-auto', and 'auto'.
    """
    def __init__(self, mode: str = None, audit_logger: AuditLogger = None, llm: Any = None):
        """
        Initialize the FixExecutor.
        
        Args:
            mode: 'suggest' | 'semi-auto' | 'auto'. If None, reads from FIX_MODE env variable, defaulting to 'suggest'.
            audit_logger: AuditLogger instance to record actions. If None, initializes a default one.
            llm: LangChain LLM instance to power the PromptOptimizer.
        """
        if mode is None:
            mode = os.getenv("FIX_MODE", "suggest")
            
        if mode not in ["suggest", "semi-auto", "auto"]:
            raise ValueError(f"Invalid execution mode '{mode}'. Must be one of: 'suggest', 'semi-auto', 'auto'.")
            
        self.mode = mode
        self.audit_logger = audit_logger if audit_logger is not None else AuditLogger()
        self.llm = llm
        logger.info(f"FixExecutor initialized in '{self.mode}' mode.")

    def execute(self, fix_plan: Dict[str, Any], approved: bool = False) -> Dict[str, Any]:
        """
        Execute the corrective fix plan based on the executor's mode and approval status.
        
        Args:
            fix_plan: Dict detailing the fix action (e.g., action type, targets, parameters).
            approved: Boolean indicating whether human approval has been given (relevant in semi-auto mode).
            
        Returns:
            Dict containing execution status and outcome details.
        """
        action_name = fix_plan.get("action", "unknown")
        
        if self.mode == "suggest":
            logger.info(f"Suggesting fix action '{action_name}' without execution.")
            self.audit_logger.log_action(
                agent_id="FixExecutor",
                action=f"suggest_{action_name}",
                outcome="suggested",
                details=fix_plan
            )
            return {"status": "suggested", "plan": fix_plan}
            
        elif self.mode == "semi-auto" and not approved:
            logger.info(f"Fix action '{action_name}' requires human approval in semi-auto mode.")
            self.audit_logger.log_action(
                agent_id="FixExecutor",
                action=f"request_approval_{action_name}",
                outcome="pending_approval",
                details=fix_plan
            )
            return {"status": "pending_approval", "plan": fix_plan}
            
        elif self.mode == "auto" or (self.mode == "semi-auto" and approved):
            logger.info(f"Applying fix action '{action_name}' (mode: {self.mode}, approved: {approved}).")
            return self._apply_fix(fix_plan)
            
        else:
            return {"status": "error", "error": "Inconsistent state between mode and approval flags."}

    def _apply_fix(self, fix_plan: Dict[str, Any]) -> Dict[str, Any]:
        """Routes and applies the specific healing action."""
        action = fix_plan.get("action")
        
        try:
            if action == "rewrite_prompt":
                return self._rewrite_prompt(fix_plan)
            elif action == "update_config":
                return self._update_config(fix_plan)
            elif action == "alert_retrain":
                return self._send_retrain_alert(fix_plan)
            else:
                err_msg = f"Unknown action: '{action}'"
                logger.error(err_msg)
                self.audit_logger.log_action(
                    agent_id="FixExecutor",
                    action=str(action),
                    outcome="failed",
                    details={"error": err_msg}
                )
                return {"status": "failed", "error": err_msg}
        except Exception as e:
            logger.exception(f"Unexpected error applying fix: {e}")
            self.audit_logger.log_action(
                agent_id="FixExecutor",
                action=str(action),
                outcome="failed",
                details={"error": str(e)}
            )
            return {"status": "failed", "error": str(e)}

    def _rewrite_prompt(self, fix_plan: Dict[str, Any]) -> Dict[str, Any]:
        """Rewrites and saves a failing prompt."""
        original = fix_plan.get("original_prompt", "")
        reason = fix_plan.get("failure_reason", "")
        target_path = fix_plan.get("filepath")
        
        # Optimize prompt using LLM if available, otherwise fallback to simple fallback optimization
        if self.llm is not None:
            optimizer = PromptOptimizer(self.llm)
            optimized_prompt = optimizer.optimize(original, reason)
        else:
            # Fallback simple rule-based optimization
            optimized_prompt = f"{original}\n\n# Aegis Auto-Correction Guardrails:\n# - Avoid: {reason}"
            
        if target_path:
            # Ensure folder exists
            os.makedirs(os.path.dirname(target_path), exist_ok=True)
            with open(target_path, "w", encoding="utf-8") as f:
                f.write(optimized_prompt)
            logger.info(f"Optimized prompt written to {target_path}")
            
        self.audit_logger.log_action(
            agent_id="FixExecutor",
            action="rewrite_prompt",
            outcome="success",
            details={
                "target_file": target_path,
                "reason": reason,
                "original_length": len(original),
                "optimized_length": len(optimized_prompt)
            }
        )
        return {
            "status": "success",
            "action": "rewrite_prompt",
            "filepath": target_path,
            "optimized_prompt": optimized_prompt
        }

    def _update_config(self, fix_plan: Dict[str, Any]) -> Dict[str, Any]:
        """Updates configuration key/value pairs in settings YAML."""
        config_path = fix_plan.get("filepath", "config/settings.yaml")
        key = fix_plan.get("config_key")
        value = fix_plan.get("config_value")
        
        if not key:
            raise ValueError("No 'config_key' specified in update_config fix plan.")
            
        # Load existing yaml
        config_data = {}
        if os.path.exists(config_path):
            with open(config_path, "r", encoding="utf-8") as f:
                config_data = yaml.safe_load(f) or {}
                
        # Parse dot notation key (e.g. "thresholds.drift_psi")
        parts = key.split(".")
        ref = config_data
        for part in parts[:-1]:
            if part not in ref or not isinstance(ref[part], dict):
                ref[part] = {}
            ref = ref[part]
        ref[parts[-1]] = value
        
        # Save back to yaml
        os.makedirs(os.path.dirname(config_path), exist_ok=True)
        with open(config_path, "w", encoding="utf-8") as f:
            yaml.safe_dump(config_data, f, default_flow_style=False)
            
        logger.info(f"Updated config key '{key}' to '{value}' in {config_path}")
        
        self.audit_logger.log_action(
            agent_id="FixExecutor",
            action="update_config",
            outcome="success",
            details={
                "filepath": config_path,
                "config_key": key,
                "config_value": value
            }
        )
        return {
            "status": "success",
            "action": "update_config",
            "filepath": config_path,
            "config_key": key,
            "config_value": value
        }

    def _send_retrain_alert(self, fix_plan: Dict[str, Any]) -> Dict[str, Any]:
        """Simulates sending a retraining alert."""
        system_id = fix_plan.get("system_id", "unknown_system")
        metric_details = fix_plan.get("metric_details", {})
        
        logger.info(f"Retraining alert triggered for system: {system_id}.")
        
        self.audit_logger.log_action(
            agent_id="FixExecutor",
            action="alert_retrain",
            outcome="success",
            details={
                "system_id": system_id,
                "metric_details": metric_details
            }
        )
        return {
            "status": "success",
            "action": "alert_retrain",
            "system_id": system_id,
            "alert_sent": True
        }
